#---- Directory structure config ----
draft_dir: "drafts"
fastq_dir: "fastq"
out_dir: "results"
log_dir: "logs"
cluster_log_dir: "cluster_logs"
error_dir: "errors"
benchmark_dir: "benchmarks"
conda_config: "workflow/envs/conda.yaml"
#---- Tool threads ----
bwa_index_threads: 1
faidx_threads: 1
restriction_sites_threads: 1
juicer_threads: 30
bwa_threads: 10
#---- Tool memory ----
bwa_index_mem_mb: 10000
faidx_mem_mb: 5000
restriction_sites_mem_mb: 5000
juicer_mem_mb: 50000
bwa_mem_mb: 50000
#---- Tool time ----
bwa_index_time: "12:00:00"
faidx_time: "00:30:00"
restriction_sites_time: "12:00:00"
juicer_time: "100:00:00"
bwa_time: "48:00:00"
#---- Tool partition ----
default_partition: "common"
bwa_index_partition: ""
faidx_partition: ""
restriction_sites_partition: ""
juicer_partition: ""
bwa_partition: ""
#---- Tool variables ----
restrictase: "MboI"
